from classes.Question import Question

questions = [
    Question("What is the capital of France?", "Paris"),
    Question("What is the capital of Germany?", "Berlin"),
    Question("What is the capital of Italy?", "Rome"),
    Question("What is the capital of Spain?", "Madrid"),
    Question("What is the capital of Portugal?", "Lisbon"),
    Question("What is the capital of Greece?", "Athens"),
    Question("What is the capital of Turkey?", "Istanbul"),
    Question("What is the capital of Egypt?", "Cairo"),
    Question("What is the capital of Syria?", "Damascus"),
    Question("What is the capital of Iraq?", "Baghdad"),
    Question("What is the capital of Saudi Arabia?", "Riyadh"),
    Question("What is the capital of Morocco?", "Rabat"),
    Question("What is the capital of Tunisia?", "Tunis"),
    Question("What is the capital of Algeria?", "Algiers"),
    Question("What is the capital of Libya?", "Tripoli"),
    Question("What is the capital of Jordan?", "Amman"),
    Question("What is the capital of Lebanon?", "Beirut"),
    Question("How much range does a fully upgrade Longbow have in Age of Empires 2?", "12"),
    Question("What is the largest planet in our solar system?", "Jupiter"),
    Question("Which artist painted the famous painting 'The Starry Night'?", "Vincent van Gogh"),
    Question("What is the chemical symbol for gold?", "Au"),
    Question("In which country was the first Olympic Games held?", "Greece"),
    Question("Who wrote the famous novel 'To Kill a Mockingbird'?", "Harper Lee"),
    Question("What is the smallest country in the world, both in terms of population and land area?", "Vatican City"),
    Question("Who was the first President of the United States?", "George Washington"),
    Question("What is the largest living species of lizard?", "Komodo dragon"),
    Question("In which year did the first iPhone come out?", "2007"),
    Question("Who was the lead singer of the rock band Queen?", "Freddie Mercury"),
    Question("Which civilization is known for its unique unit, the Samurai?", "Japanese"),
    Question("Which civilization has a unique technology that increases the range of their archers?", "Britons"),
    Question("What is the largest mammal on Earth?", "Blue whale"),
    Question("Which planet in our solar system is known as the 'Red Planet'?", "Mars"),
    Question("Who painted the famous painting 'The Mona Lisa'?", "Leonardo da Vinci"),
    Question("What is the chemical symbol for silver?", "Ag"),
    Question("In which country was the first permanent English settlement established?", "United States"),
    Question("Who wrote the famous novel 'Pride and Prejudice'?", "Jane Austen"),
    Question("What is the smallest state in the United States?", "Rhode Island"),
    Question("Who was the first President of France?", "Napoleon"),
    Question("What is the largest city in Scandinavia?", "Stockholm"),
    Question("Who was the lead singer of the rock band Guns N' Roses?", "Axl Rose"),
    Question("What is the highest mountain peak in North America?", "Denali"),
    Question("In which year did the first human walk on the Moon?", "1969"),
    Question("Who was the ancient Greek goddess of wisdom?", "Athena"),
    Question("What is the largest island in the Mediterranean Sea?", "Sicily"),
    Question("Who wrote the famous play 'Romeo and Juliet'?", "William Shakespeare"),
    Question("What is the smallest country in South America?", "Suriname"),
    Question("What is the largest city in Australia?", "Sydney"),
    Question("Who was the ancient Egyptian pharaoh who built the Great Pyramid of Giza?", "Khufu"),
    Question("What is the highest waterfall in the world?", "Angel Falls")
]